using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;

namespace NESOOP.Compiler
{
    public static class Compiler
    {
        public static void Compile(string sourcePath, string outputPath)
        {
            string source = File.ReadAllText(sourcePath);

            // ----------------------------------------------------------
            // TEMPORARY stage-0 compiler
            //
            // For now we recognize only:
            //
            // Screen.BackgroundColor = 0x21;
            //
            // Later this gets replaced by:
            // Lexer -> Parser -> AST -> Type checker -> Code generator
            // ----------------------------------------------------------

            Match match = Regex.Match(
                source,
                @"Screen\.BackgroundColor\s*=\s*(0x[0-9A-Fa-f]{1,2}|\$[0-9A-Fa-f]{1,2}|\d{1,3})\s*;"
            );

            if (!match.Success)
            {
                throw new Exception(
                    "Compiler error: expected Screen.BackgroundColor assignment."
                );
            }

            string valueText = match.Groups[1].Value;

            int value;

            if (valueText.StartsWith("0x"))
            {
                value = Convert.ToInt32(valueText[2..], 16);
            }
            else if (valueText.StartsWith("$"))
            {
                value = Convert.ToInt32(valueText[1..], 16);
            }
            else
            {
                value = int.Parse(valueText);
            }

            if (value < 0 || value > 0x3F)
            {
                throw new Exception(
                    "Background color must be between 0x00 and 0x3F."
                );
            }

            string assembly = $@"
; ==========================================================
; GENERATED BY NesOop.Compiler
; DO NOT EDIT MANUALLY
; ==========================================================

.segment ""CODE""

.export Game_Start

.proc Game_Start

    ; Reset PPU address latch
    lda $2002

    ; Palette address $3F00
    lda #$3F
    sta $2006

    lda #$00
    sta $2006

    ; Background colour from NES OOP source
    lda #${value:X2}
    sta $2007

    rts

.endproc
";

            string? directory = Path.GetDirectoryName(outputPath);

            if (directory != null)
                Directory.CreateDirectory(directory);

            File.WriteAllText(outputPath, assembly);

            Console.WriteLine(
                $"Compiled: {Path.GetFileName(sourcePath)}"
            );

            Console.WriteLine(
                $"Generated: {outputPath}"
            );
        }
    }
}
