using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;

namespace NESOOP.Compiler
{
    public static class Compiler
    {
        public static void Compile(
            string sourcePath,
            string outputPath
        )
        {
            string source =
                File.ReadAllText(sourcePath);


            // ----------------------------------------------------------
            // Lexer
            // ----------------------------------------------------------

            Lexer lexer = new(source);

            List<Token> tokens =
                lexer.Lex();


            // ----------------------------------------------------------
            // Parser
            // ----------------------------------------------------------

            Parser parser = new(tokens);

            CompilationUnitSyntax program =
                parser.Parse();


            // ----------------------------------------------------------
            // TEMPORARY semantic/code-generation step
            //
            // Find:
            //
            // class Game
            //     static void Start()
            //
            // and inside it:
            //
            // Screen.BackgroundColor = ...
            //
            // ----------------------------------------------------------

            ClassDeclarationSyntax? gameClass =
                program.Classes.FirstOrDefault(
                    x => x.Name == "Game"
                );

            if (gameClass == null)
            {
                throw new Exception(
                    "Compiler error: class Game was not found."
                );
            }


            MethodDeclarationSyntax? startMethod =
                gameClass.Methods.FirstOrDefault(
                    x =>
                        x.Name == "Start" &&
                        x.IsStatic
                );

            if (startMethod == null)
            {
                throw new Exception(
                    "Compiler error: static void Game.Start() was not found."
                );
            }


            AssignmentStatementSyntax? colorAssignment =
                startMethod.Body.Statements
                    .OfType<AssignmentStatementSyntax>()
                    .FirstOrDefault(
                        x =>
                            x.Target.Parts.Count == 2 &&
                            x.Target.Parts[0] == "Screen" &&
                            x.Target.Parts[1] == "BackgroundColor"
                    );


            if (colorAssignment == null)
            {
                throw new Exception(
                    "Compiler error: " +
                    "Screen.BackgroundColor assignment was not found."
                );
            }


            int value =
                colorAssignment.Value.Value;


            if (value < 0 || value > 0x3F)
            {
                Token token =
                    colorAssignment.Value.Token;

                throw new Exception(
                    $"Background color must be between " +
                    $"0x00 and 0x3F at " +
                    $"line {token.Line}, " +
                    $"column {token.Column}."
                );
            }


            // ----------------------------------------------------------
            // Generate 6502 assembly
            // ----------------------------------------------------------

            string assembly = $@"
; ==========================================================
; GENERATED BY NesOop.Compiler
; DO NOT EDIT MANUALLY
; ==========================================================

.segment ""CODE""

.export Game_Start

.proc Game_Start

    lda $2002

    lda #$3F
    sta $2006

    lda #$00
    sta $2006

    lda #${value:X2}
    sta $2007

    rts

.endproc
";


            string? directory =
                Path.GetDirectoryName(outputPath);

            if (directory != null)
            {
                Directory.CreateDirectory(directory);
            }


            File.WriteAllText(
                outputPath,
                assembly
            );


            Console.WriteLine(
                $"Compiled: {Path.GetFileName(sourcePath)}"
            );

            Console.WriteLine(
                $"Generated: {outputPath}"
            );
        }
    }
}
