using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;

namespace NESOOP.Compiler
{
    public static class Compiler
    {
        public static void Compile(
            string sourcePath,
            string outputPath
        )
        {
            string source = File.ReadAllText(sourcePath);


            // ----------------------------------------------------------
            // Lexical analysis
            // ----------------------------------------------------------

            Lexer lexer = new(source);

            List<Token> tokens = lexer.Lex();


            Console.WriteLine();
            Console.WriteLine("Tokens:");
            Console.WriteLine("------------------------------");

            foreach (Token token in tokens)
            {
                Console.WriteLine(token);
            }

            Console.WriteLine();


            // ----------------------------------------------------------
            // TEMPORARY:
            //
            // Find:
            //
            // Screen.BackgroundColor = NUMBER;
            //
            // This gets replaced by the real parser next.
            // ----------------------------------------------------------

            Token? colorToken = null;


            for (int i = 0; i < tokens.Count - 5; i++)
            {
                if (
                    tokens[i].Kind == TokenKind.Identifier &&
                    tokens[i].Text == "Screen" &&

                    tokens[i + 1].Kind == TokenKind.Dot &&

                    tokens[i + 2].Kind == TokenKind.Identifier &&
                    tokens[i + 2].Text == "BackgroundColor" &&

                    tokens[i + 3].Kind == TokenKind.Equals &&

                    tokens[i + 4].Kind == TokenKind.Number &&

                    tokens[i + 5].Kind == TokenKind.Semicolon
                )
                {
                    colorToken = tokens[i + 4];

                    break;
                }
            }


            if (colorToken == null)
            {
                throw new Exception(
                    "Compiler error: " +
                    "expected Screen.BackgroundColor assignment."
                );
            }


            int value = ParseNumber(
                colorToken.Value
            );


            if (value < 0 || value > 0x3F)
            {
                throw new Exception(
                    $"Background color must be between " +
                    $"0x00 and 0x3F at " +
                    $"line {colorToken.Value.Line}, " +
                    $"column {colorToken.Value.Column}."
                );
            }


            // ----------------------------------------------------------
            // Generate assembly
            // ----------------------------------------------------------

            string assembly = $@"
; ==========================================================
; GENERATED BY NesOop.Compiler
; DO NOT EDIT MANUALLY
; ==========================================================

.segment ""CODE""

.export Game_Start

.proc Game_Start

    ; Reset PPU address latch
    lda $2002

    ; Palette address $3F00
    lda #$3F
    sta $2006

    lda #$00
    sta $2006

    ; Background colour from NES OOP source
    lda #${value:X2}
    sta $2007

    rts

.endproc
";


            string? directory =
                Path.GetDirectoryName(outputPath);

            if (directory != null)
            {
                Directory.CreateDirectory(directory);
            }


            File.WriteAllText(
                outputPath,
                assembly
            );


            Console.WriteLine(
                $"Compiled: {Path.GetFileName(sourcePath)}"
            );

            Console.WriteLine(
                $"Generated: {outputPath}"
            );
        }


        private static int ParseNumber(Token token)
        {
            string text = token.Text;


            if (
                text.StartsWith("0x") ||
                text.StartsWith("0X")
            )
            {
                return Convert.ToInt32(
                    text[2..],
                    16
                );
            }


            return int.Parse(text);
        }
    }
}
