using System;
using System.Collections.Generic;
using System.Text;

namespace NESOOP.Compiler
{
    public sealed class Nes6502CodeGenerator
    {
        private const string ExpressionTemp =
            "__nesoop_expr_temp";


        public string Generate(
            SemanticProgram program
        )
        {
            StringBuilder output =
                new();


            output.AppendLine(
                "; =========================================================="
            );

            output.AppendLine(
                "; GENERATED BY NesOop.Compiler"
            );

            output.AppendLine(
                "; =========================================================="
            );

            output.AppendLine();


            // =========================================================
            // RAM
            // =========================================================

            output.AppendLine(
                ".segment \"BSS\""
            );

            output.AppendLine();


            output.AppendLine(
                $"{ExpressionTemp}: .res 1"
            );


            // Parameters
            foreach (
                SemanticParameter parameter
                in program.Methods
                    .SelectMany(
                        method =>
                            method.Parameters
                    )
            )
            {
                output.AppendLine(
                    $"{parameter.StorageName}: .res 1"
                );
            }


            // Locals
            foreach (
                SemanticByteDeclaration variable
                in program.Methods
                    .SelectMany(
                        method =>
                            method.Statements
                    )
                    .OfType<SemanticByteDeclaration>()
            )
            {
                output.AppendLine(
                    $"{variable.StorageName}: .res 1"
                );
            }


            output.AppendLine();


            // =========================================================
            // CODE
            // =========================================================

            output.AppendLine(
                ".segment \"CODE\""
            );

            output.AppendLine();


            output.AppendLine(
                ".export Game_Start"
            );

            output.AppendLine();


            foreach (
                SemanticMethod method
                in program.Methods
            )
            {
                GenerateMethod(
                    output,
                    method
                );
            }


            return output.ToString();
        }


        private static void GenerateMethod(
            StringBuilder output,
            SemanticMethod method
        )
        {
            output.AppendLine(
                $"; {method.ClassName}.{method.Name}()"
            );


            output.AppendLine(
                $".proc {method.Label}"
            );

            output.AppendLine();


            foreach (
                SemanticStatement statement
                in method.Statements
            )
            {
                GenerateStatement(
                    output,
                    statement
                );
            }


            // If there wasn't an explicit return,
            // void methods automatically RTS.
            if (
                method.Statements.Count == 0 ||
                method.Statements[^1]
                is not SemanticReturnStatement
            )
            {
                output.AppendLine(
                    "    rts"
                );
            }


            output.AppendLine();

            output.AppendLine(
                ".endproc"
            );

            output.AppendLine();
        }


        private static void GenerateStatement(
            StringBuilder output,
            SemanticStatement statement
        )
        {
            // =========================================================
            // Local variable
            // =========================================================

            if (
                statement
                is SemanticByteDeclaration variable
            )
            {
                GenerateLoadValue(
                    output,
                    variable.Initializer
                );


                output.AppendLine(
                    $"    sta {variable.StorageName}"
                );

                output.AppendLine();

                return;
            }


            // =========================================================
            // Assignment
            // =========================================================

            if (
                statement
                is SemanticVariableAssignment assignment
            )
            {
                GenerateLoadValue(
                    output,
                    assignment.Value
                );


                output.AppendLine(
                    $"    sta {assignment.StorageName}"
                );

                output.AppendLine();

                return;
            }


            // =========================================================
            // Method-call statement
            // =========================================================

            if (
                statement
                is SemanticMethodCallStatement call
            )
            {
                GenerateCall(
                    output,
                    call.Call
                );


                output.AppendLine();

                return;
            }


            // =========================================================
            // Return
            // =========================================================

            if (
                statement
                is SemanticReturnStatement returnStatement
            )
            {
                if (returnStatement.Value != null)
                {
                    // Leave returned byte in A.
                    GenerateLoadValue(
                        output,
                        returnStatement.Value
                    );
                }


                output.AppendLine(
                    "    rts"
                );

                output.AppendLine();

                return;
            }


            // =========================================================
            // Background colour
            // =========================================================

            if (
                statement
                is SemanticBackgroundColorAssignment background
            )
            {
                output.AppendLine(
                    "    lda $2002"
                );

                output.AppendLine();

                output.AppendLine(
                    "    lda #$3F"
                );

                output.AppendLine(
                    "    sta $2006"
                );

                output.AppendLine();

                output.AppendLine(
                    "    lda #$00"
                );

                output.AppendLine(
                    "    sta $2006"
                );

                output.AppendLine();


                GenerateLoadValue(
                    output,
                    background.Value
                );


                output.AppendLine(
                    "    and #$3F"
                );

                output.AppendLine(
                    "    sta $2007"
                );

                output.AppendLine();

                return;
            }


            throw new Exception(
                "Internal compiler error: unknown statement."
            );
        }


        // =============================================================
        // Load a semantic value into A
        // =============================================================

        private static void GenerateLoadValue(
            StringBuilder output,
            SemanticValue value
        )
        {
            switch (value)
            {
                case SemanticByteLiteral literal:

                    output.AppendLine(
                        $"    lda #${literal.Value:X2}"
                    );

                    return;


                case SemanticVariableReference variable:

                    output.AppendLine(
                        $"    lda {variable.StorageName}"
                    );

                    return;


                case SemanticBinaryAdd add:

                    GenerateLoadValue(
                        output,
                        add.Left
                    );


                    output.AppendLine(
                        "    pha"
                    );


                    GenerateLoadValue(
                        output,
                        add.Right
                    );


                    output.AppendLine(
                        $"    sta {ExpressionTemp}"
                    );


                    output.AppendLine(
                        "    pla"
                    );


                    output.AppendLine(
                        "    clc"
                    );


                    output.AppendLine(
                        $"    adc {ExpressionTemp}"
                    );


                    return;


                case SemanticMethodCallValue call:

                    GenerateCall(
                        output,
                        call.Call
                    );

                    // Result is already in A.
                    return;


                default:

                    throw new Exception(
                        "Internal compiler error: cannot load value."
                    );
            }
        }


        // =============================================================
        // Calling convention
        // =============================================================

        private static void GenerateCall(
            StringBuilder output,
            SemanticCall call
        )
        {
            // Copy each argument into the target method's
            // parameter RAM slot.
            for (
                int i = 0;
                i < call.Arguments.Count;
                i++
            )
            {
                GenerateLoadValue(
                    output,
                    call.Arguments[i]
                );


                output.AppendLine(
                    $"    sta {call.ParameterStorageNames[i]}"
                );
            }


            output.AppendLine(
                $"    jsr {call.TargetLabel}"
            );


            // If this is a byte-returning method,
            // its return value is now in A.
        }
    }
}
