using System;
using System.Collections.Generic;
using System.Text;

namespace NESOOP.Compiler
{
    public sealed class Nes6502CodeGenerator
    {
        public string Generate(
            SemanticProgram program
        )
        {
            return $@"
; ==========================================================
; GENERATED BY NesOop.Compiler
; DO NOT EDIT MANUALLY
; ==========================================================

.segment ""CODE""

.export Game_Start


.proc Game_Start

    ; Reset PPU address latch
    lda $2002

    ; Select palette address $3F00
    lda #$3F
    sta $2006

    lda #$00
    sta $2006

    ; Screen.BackgroundColor
    lda #${program.BackgroundColor:X2}
    sta $2007

    rts

.endproc
";
        }
    }
}
