using System;
using System.Collections.Generic;
using System.Text;

namespace NESOOP.Compiler
{
    public sealed class Nes6502CodeGenerator
    {
        public string Generate(
            SemanticProgram program
        )
        {
            StringBuilder output = new();


            output.AppendLine(
                "; =========================================================="
            );

            output.AppendLine(
                "; GENERATED BY NesOop.Compiler"
            );

            output.AppendLine(
                "; DO NOT EDIT MANUALLY"
            );

            output.AppendLine(
                "; =========================================================="
            );

            output.AppendLine();


            // =========================================================
            // RAM allocation
            // =========================================================

            output.AppendLine(
                ".segment \"BSS\""
            );

            output.AppendLine();


            foreach (
                SemanticByteDeclaration variable
                in program.Statements
                    .OfType<SemanticByteDeclaration>()
            )
            {
                output.AppendLine(
                    $"{variable.StorageName}: .res 1"
                );
            }


            output.AppendLine();


            // =========================================================
            // Code
            // =========================================================

            output.AppendLine(
                ".segment \"CODE\""
            );

            output.AppendLine();

            output.AppendLine(
                ".export Game_Start"
            );

            output.AppendLine();

            output.AppendLine(
                ".proc Game_Start"
            );

            output.AppendLine();


            foreach (
                SemanticStatement statement
                in program.Statements
            )
            {
                GenerateStatement(
                    output,
                    statement
                );
            }


            output.AppendLine(
                "    rts"
            );

            output.AppendLine();

            output.AppendLine(
                ".endproc"
            );


            return output.ToString();
        }


        private static void GenerateStatement(
            StringBuilder output,
            SemanticStatement statement
        )
        {
            // =========================================================
            // byte variable
            // =========================================================

            if (
                statement
                is SemanticByteDeclaration variable
            )
            {
                output.AppendLine(
                    $"    ; byte {variable.Name} = ${variable.InitialValue:X2}"
                );

                output.AppendLine(
                    $"    lda #${variable.InitialValue:X2}"
                );

                output.AppendLine(
                    $"    sta {variable.StorageName}"
                );

                output.AppendLine();

                return;
            }


            // =========================================================
            // Screen.BackgroundColor = ...
            // =========================================================

            if (
                statement
                is SemanticBackgroundColorAssignment background
            )
            {
                output.AppendLine(
                    "    ; Screen.BackgroundColor"
                );


                // Select palette address $3F00

                output.AppendLine(
                    "    lda $2002"
                );

                output.AppendLine();

                output.AppendLine(
                    "    lda #$3F"
                );

                output.AppendLine(
                    "    sta $2006"
                );

                output.AppendLine();

                output.AppendLine(
                    "    lda #$00"
                );

                output.AppendLine(
                    "    sta $2006"
                );

                output.AppendLine();


                GenerateLoadValue(
                    output,
                    background.Value
                );


                output.AppendLine(
                    "    sta $2007"
                );

                output.AppendLine();

                return;
            }


            throw new Exception(
                "Internal compiler error: " +
                "unknown semantic statement."
            );
        }


        private static void GenerateLoadValue(
            StringBuilder output,
            SemanticValue value
        )
        {
            switch (value)
            {
                case SemanticByteLiteral literal:

                    output.AppendLine(
                        $"    lda #${literal.Value:X2}"
                    );

                    return;


                case SemanticVariableReference variable:

                    output.AppendLine(
                        $"    lda {variable.StorageName}"
                    );

                    return;


                default:

                    throw new Exception(
                        "Internal compiler error: " +
                        "cannot load semantic value."
                    );
            }
        }
    }
}
